accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('login/url/', views.RequestLoginViaUrlView.as_view(), name='request_login_via_url'),
    path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.MyPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:id>/', views.post_detail, name='post_detail'),
    path('post/<int:id>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<int:id>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:id>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:id>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:id>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove/', views.comment_remove, name='comment_remove'),
]

lemon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ddn-admin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.core.mail import send_mail

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    website_url = models.URLField(blank=True)


def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)
        
        # send mail
        send_mail(
            '반갑습니다.',
            '회원이 된 걸 환영합니다.',
            'contact@datadriven.kr',
            [user.email],
            fail_silently = False,
        )

post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['username'].validators = [validate_email]
            self.fields['username'].help_text = 'Enter E-mail Format.'
            self.fields['username'].label = 'E-mail'
            
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = user.username
        if commit:
            user.save()
        return user

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView
from django.shortcuts import render, redirect, resolve_url
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.http import Http404
from django.utils.http import urlsafe_base64_decode
from .forms import SignupForm

# signup 함수 기반 뷰
'''
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user) # 로그인 처리
            next_url = request.GET.get('next') or 'accounts:profile'
            return redirect(next_url)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })
'''

class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'

    def get_success_url(self):
        next_url = self.request.GET.get('next') or 'accounts:profile'
        return resolve_url(next_url)

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return redirect(self.get_success_url())

signup = SignupView.as_view()

@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


class RequestLoginViaUrlView(PasswordResetView):
    template_name = 'accounts/request_login_via_url_form.html'
    title = '이메일을 통한 로그인'
    email_template_name = 'accounts/login_via_url.html'
    success_url = settings.LOGIN_URL


def login_via_url(request, uidb64, token):
    User = get_user_model()
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        current_user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        raise Http404

    redirect_path = 'shop:item_list'

    if default_token_generator.check_token(current_user, token):
        auth_login(request, current_user)
        messages.info(request, '로그인이 승인되었습니다.')
        return redirect(redirect_path)

    messages.error(request, '로그인이 거부되었습니다.')
    return redirect(redirect_path)


class MyPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy('accounts:password_change_done')


class MyPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'accounts/password_change_done.html'


class MyPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    email_template_name = 'accounts/password_reset_email.html'
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        messages.info(self.request, '암호 변경 메일을 발송했습니다.')
        return super().form_valid(form)

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        messages.info(self.request, '암호 리셋을 완료했습니다.')
        return super().form_valid(form)

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

{% block content %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/layout.html" %}

{% block content %}
  <h2>로그인</h2>

  <form method="post" action="">
  {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>

      <input type="submit" value="login" />
  </form>
  <hr>
  <div>
    <a href="{% url 'accounts:request_login_via_url' %}">이메일로 로그인하기</a>
  </div>
  <div>
    <a href="{% url 'accounts:password_reset' %}">이메일로 암호 재설정하기</a>
  </div>
{% endblock %}

accounts/templates/accounts/login_via_url.html
아래 주소를 통해 {{ site_name }}에 로그인하실 수 있습니다.

링크: {{ protocol }}://{{ domain }}{% url 'accounts:login_via_url' uidb64=uid token=token %}

accounts/templates/accounts/password_change_done.html
{% extends "accounts/layout.html" %}

{% block content %}
  <h2>암호 변경 완료</h2>

  암호 변경을 완료했습니다.
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "accounts/layout.html" %}

{% block content %}
  <h2>암호 변경</h2>

  <form method="post" action="">
  {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>

      <input type="submit" />
  </form>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/layout.html" %}

{% block content %}
  <h2>새 비밀번호 설정</h2>

  <form method="post" action="">
  {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>

      <input type="submit" />
  </form>
  <hr/>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends "accounts/layout.html" %}

{% block content %}
  <h2>암호 리셋 요청하기</h2>

  <form method="post" action="">
  {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>

      <input type="submit" />
  </form>
  <hr/>

  <a href="{% url 'accounts:login' %}">로그인</a>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
  <h2>{{user}}'s profile</h2>
  <h3>e-mail</h3>
  {{ user.email|default:'&dash;' }}
  
  <h3>bio</h3>
  {{ user.profile.bio|default:'&dash;' }}
  
  <hr/>
  
  <a href="{% url 'accounts:password_change' %}">암호 변경하기</a>
{% endblock %}

accounts/templates/accounts/request_login_via_url_form.html
{% extends "accounts/layout.html" %}

{% block content %}
  <h2>이메일로 로그인</h2>
  
  <form action="" method="post">
       {% csrf_token %}
       <table>
           {{ form.as_table }}
       </table>
       <input type="submit" />
   </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content %}
  <form method="post" action="">
  {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>

      <input type="submit" value="submit" />
  </form>
{% endblock %}