blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:id>/', views.post_detail, name='post_detail'),
    path('post/<int:id>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<int:id>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:id>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:id>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:id>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove/', views.comment_remove, name='comment_remove'),
]

lemon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ddn-admin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from lemon.utils import uuid_upload_to


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'id': self.pk})

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text', 'photo']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['author', 'text']

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm


def post_list(request):
    qs = Post.objects.all()
    qs = qs.filter(published_date__lte=timezone.now())
    qs = qs.order_by('-published_date')

    return render(request, 'blog/post_list.html', {
        'post_list': qs,
    })


@login_required
def post_draft_list(request):
    qs = Post.objects.all()
    qs = qs.filter(published_date__isnull=True)
    qs = qs.order_by('created_date')

    return render(request, 'blog/post_draft_list.html', {
        'post_list': qs,
    })


def post_detail(request, id):
    # try:
    #     post = Post.objects.get(pk=id)\
    # except Post.DoesNotExist:
    #     raise Http404
    post = get_object_or_404(Post, pk=id)

    return render(request, 'blog/post_detail.html', {
        'post': post,
    })


@login_required
def post_new(request, post=None):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(post)
    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_edit.html', {
        'form': form,
    })


@login_required
def post_edit(request, id):
    post = get_object_or_404(Post, pk=id)
    return post_new(request, post)


@login_required
def post_publish(request, id):
    post = get_object_or_404(Post, pk=id)
    post.publish()
    return redirect('blog:post_detail', id=post.id)


@login_required
def post_remove(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect('blog:post_list')


def add_comment_to_post(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', id=post.id)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required
def comment_approve(request, id):
    comment = get_object_or_404(Comment, pk=id)
    comment.approve()
    return redirect('post_detail', id=comment.post.id)


@login_required
def comment_remove(request, id):
    comment = get_object_or_404(Comment, pk=id)
    comment.delete()
    return redirect('post_detail', id=comment.post.id)

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/layout.html' %}

{% block blog_content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <title>Lemon Project</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
        <link rel="stylesheet" href="{% static 'blog/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
          {% if user.is_authenticated %}
            <a href="{% url 'post_new' %}" class="top-menu">
              <span class="glyphicon glyphicon-plus"></span>
            </a>
            <a href="{% url 'post_draft_list' %}" class="top-menu">
              <span class="glyphicon glyphicon-edit"></span>
            </a>
            <p class="top-menu">
              Hello, {{ user.username }}
              <small>
                (<a href="{% url 'logout' %}">Log out</a>)
              </small>
            </p>
          {% else %}
            <a href="{% url 'login' %}?next={{ request.path }}" class="top-menu">
              <span class="glyphicon glyphicon-lock"></span>
            </a>
          {% endif %}
          <h1><a href="/blog/">Lemon's Blog</a></h1>
        </div>
        <div class="content container">
          <div class="row">
            <div class="col-md-8">
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div>
    </body>
</html>

blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load static fresh_static %}

{% block title %}
  Blog by Lemon Project
{% endblock %}

{% block extra_head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% fresh_static 'blog/blog.css' %}">
{% endblock %}

{% block extra_body %}
  {{ block.super }}
{% endblock %}

{% block auth_user_page_header %}
  <a href="{% url 'blog:post_new' %}" class="top-menu">
    <span class="glyphicon glyphicon-plus"></span>
  </a>
  <a href="{% url 'blog:post_draft_list' %}" class="top-menu">
    <span class="glyphicon glyphicon-edit"></span>
  </a>
{% endblock %}

{% block content %}
  <h1>Lemon's Blog</h1>
  <hr>
  {% block blog_content %}
  {% endblock %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block blog_content %}
  <div class="post">
    {% if post.published_date %}
      <div class="date">
        {{ post.published_date }}
      </div>
    {% else %}
      <a class="btn btn-default" href="{% url 'blog:post_publish' post.id %}">Publish</a>
    {% endif %}
    {% if user.is_authenticated %}
      <a class="btn btn-default" href="{% url 'blog:post_edit' post.id %}">
        <span class="glyphicon glyphicon-pencil"></span>
      </a>
      <a class="btn btn-default" onclick="return confirm('Are you sure?')" href="{% url 'blog:post_remove' post.id %}">
        <span class="glyphicon glyphicon-remove"></span>
      </a>
    {% endif %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.text|linebreaks }}</p>
    {% if post.photo %}
      <img src="{{ post.photo.url }}" style="max-width: 100%;"><br>
    {% endif %}
  </div>
  <hr>
  <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' post.id %}">Add comment</a>
  {% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
      <div class="comment">
          <div class="date">
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default"
                  href="{% url 'blog:comment_remove' id=comment.id %}"
                  onclick="return confirm('Are you sure?')">
                  <span class="glyphicon glyphicon-remove"></span>
                </a>
                <a class="btn btn-default" href="{% url 'blog:comment_approve' id=comment.id %}">
                  <span class="glyphicon glyphicon-ok"></span>
                </a>
            {% endif %}
          </div>
          <strong>{{ comment.author }}</strong>
          <p>{{ comment.text|linebreaks }}</p>
      </div>
    {% endif %}
  {% empty %}
      <div class="comment"><p>No comments here yet :(</p></div>
  {% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends "blog/layout.html" %}

{% block blog_content %}
  {% for post in post_list %}
    <div class="post">
      <div class="date">
        <p>created: {{ post.created_date|date:'Y-m-d' }}</p>
      </div>
      <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
      <p>{{ post.text|truncatechars:200 }}</p>
      <hr>
    </div>
  {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/layout.html' %}

{% block blog_content %}
    <h1>New post</h1>
    <form method="POST" enctype="multipart/form-data" class="post-form" autocomplete="off">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block blog_content %}
  {% for post in post_list %}
    <div class="post">
      <div class="date">
        <p>published: {{ post.published_date }}</p>
      </div>
      <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
      <a href="{{ post.get_absolute_url }}">Comments: {{ post.approved_comments.count }}</a>
      <hr>
    </div>
  {% endfor %}
{% endblock %}