blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:id>/', views.post_detail, name='post_detail'),
    path('post/<int:id>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<int:id>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:id>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:id>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:id>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove/', views.comment_remove, name='comment_remove'),
]

lemon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ddn-admin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

shop/urls.py
from django.urls import path, register_converter
from .converters import FourDigitYearConverter
from . import views

register_converter(FourDigitYearConverter, 'yyyy')

app_name = 'shop'

urlpatterns = [
    path('archives/<yyyy:year>/', views.archives_year, name='archives_year'),
    path('', views.item_list, name='item_list'),
    path('item/new/', views.item_new, name='item_new'),
    path('item/<int:id>/', views.item_detail, name='item_detail'),
    path('item/<int:id>/edit', views.item_edit, name='item_edit'),
    path('item/<int:id>/remove/', views.item_remove, name='item_remove'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from lemon.utils import uuid_upload_to


class Item(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    photo = models.ImageField(upload_to=uuid_upload_to)
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'<{self.pk}> {self.name}'

    def get_absolute_url(self):
        return reverse('shop:item_detail', kwargs={'id': self.pk})

shop/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = '__all__'

shop/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm

logger = logging.getLogger(__name__)


def archives_year(request, year):
    return HttpResponse('{}년도..'.format(year))


def item_list(request):
    qs = Item.objects.all()

    word = request.GET.get('word', '')
    if word:
        qs = qs.filter(name__icontains=word)
        logger.debug(f'query: {word}')

    return render(request, 'shop/item_list.html', {
        'item_list': qs,
        'word': word,
    })


def item_detail(request, id):
    item = get_object_or_404(Item, pk=id)
    return render(request, 'shop/item_detail.html', {
        'item': item,
    })


@login_required
def item_new(request, item=None):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item = form.save()
            return redirect(item)
    else:
        form = ItemForm(instance=item)

    return render(request, 'shop/item_edit.html', {
        'form': form,
    })


@login_required
def item_edit(request, id):
    item = get_object_or_404(Item, pk=id)
    return item_new(request, item)


@login_required
def item_remove(request, id):
    item = get_object_or_404(Item, pk=id)
    item.delete()
    return redirect('shop:item_list')

shop/templates/shop/item_detail.html
{% extends "shop/layout.html" %}

{% load humanize %}

{% block shop_content %}
  <div class="item">
    {% if user.is_authenticated %}
      <a class="btn btn-default" href="{% url 'shop:item_edit' item.id %}">
        <span class="glyphicon glyphicon-pencil"></span>
      </a>
      <a class="btn btn-default" onclick="return confirm('Are you sure?')" href="{% url 'shop:item_remove' item.id %}">
        <span class="glyphicon glyphicon-remove"></span>
      </a>
    {% endif %}

    <h2>{{ item.name }}</h2>

    <p>가격: {{ item.price|intcomma }}원</p>

    {% if item.photo %}
      <img src="{{ item.photo.url }}" style="max-width: 100%;"><br>
    {% endif %}

    {% if item.desc %}
      <p>설명: {{ item.desc|linebreaks }}</p>
    {% endif %}
  </div>

  <hr>
  <a href="/shop/">목록</a>
{% endblock %}

shop/templates/shop/item_edit.html
{% extends 'shop/layout.html' %}

{% block shop_content %}
    <h1>New post</h1>
    <form method="POST" enctype="multipart/form-data" class="post-form">
      {% csrf_token %}

      <table class="table table-bordered">
        {{ form.as_table }}
      </table>
      <button type="submit" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}

{% block shop_content %}
  <form action="" method="GET">
    <input type="text" name="word" value="{{ word }}">
    <input type="submit" value="search">
  </form>

  <ul>
    {% for item in item_list %}
      <li>
        <a href="{{ item.get_absolute_url }}">
          <p>이름 : {{ item.name }}</p>
        </a>
        <p>가격 : {{ item.price }}</p>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

shop/templates/shop/item_list.jinja
<!DOCTYPE html>
<html
  <head>
    <meta charset="utf-8">
    <title>Lemon's Shop</title>
  </head>
  <body>
    <h1>Lemon's Item List</h1>

    <form action="" method="GET">
      <input type="text" name="word" value="{{ word }}">
      <input type="submit" value="search">
    </form>

    {{ user }}

    <ul>
      {% for item in item_list %}
        <li>
          <p>이름 : {{ item.name }}</p>
          <p>가격 : {{ item.price }}</p>
          <p>설명 : {{ item.desc }}</p>
        </li>
      {% endfor %}
    </ul>

  </body>
</html>

shop/templates/shop/layout.html
{% extends "layout.html" %}
{% load static fresh_static %}

{% block title %}
  Shop by Lemon Project
{% endblock %}

{% block extra_head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% fresh_static 'shop/shop.css' %}">
{% endblock %}

{% block extra_body %}
  {{ block.super }}
{% endblock %}

{% block auth_user_page_header %}
  <a href="{% url 'shop:item_new' %}" class="top-menu">
    <span class="glyphicon glyphicon-plus"></span>
  </a>
{% endblock %}

{% block content %}
  <h1>Lemon's Shop</h1>
  <hr>
  {% block shop_content %}
  {% endblock %}
{% endblock %}