accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('login/url/', views.RequestLoginViaUrlView.as_view(), name='request_login_via_url'),
    path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.MyPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:id>/', views.post_detail, name='post_detail'),
    path('post/<int:id>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<int:id>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:id>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:id>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:id>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove/', views.comment_remove, name='comment_remove'),
]

lemon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ddn-admin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

lemon/templates/layout.html
{% load static fresh_static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
        <title>
          {% block title %}
            Lemon Project
          {% endblock %}
        </title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
        {% block extra_head %}
          <link rel="stylesheet" href="{% fresh_static 'main.css' %}">
        {% endblock %}
    </head>
    <body>
        <div class="page-header">
          {% if user.is_authenticated %}
            {% block auth_user_page_header %}

            {% endblock %}
            <p class="top-menu">
              Hello, <a href="{% url 'accounts:profile' %}">{{ user.username }}</a>
              <small>
                (<a href="{% url 'accounts:logout' %}?next={{ request.path }}">Log out</a>)
              </small>
            </p>
          {% else %}
            <a href="{% url 'accounts:signup' %}?next={{ request.path }}">회원가입</a>
            <a href="{% url 'accounts:login' %}?next={{ request.path }}" class="top-menu">
              <span class="glyphicon glyphicon-lock"></span>
            </a>
          {% endif %}
          <h1><a href="/blog/">Data Driven</a></h1>
        </div>
        <div class="content container">
          <div class="row">
            <div class="col-md-8">
              {% block content %}
                <p>데이터드리븐의 웹 사이트입니다.</p>
              {% endblock %}
            </div>
          </div>
        </div>

        <hr/>

        {% if messages %}
            <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        
        <hr/>
    
        &copy;
        <script type="text/JavaScript">
          var theDate = new Date().getFullYear()
          var since = 2018
          if (theDate > since) {
            theDate = since + '-' + theDate
          }
          document.write(theDate)
        </script>
        All rights reserved by DataDriven

        {% block extra_body %}
          <script src="{% static 'main.js' %}"></script>
        {% endblock %}
    </body>
</html>